import Aside from "@/components/aside/aside";
import Header from "@/components/header/header";
import Navigation from "@/components/table/navigation";
import AsideCTXProvider from "@/context/table-ctx";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hosts Table",
  description: "Generated by create next app",
};

export default function HostTableLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navigation />
      <AsideCTXProvider>{children}</AsideCTXProvider>
    </>
  );
}
