import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AsideCTXProvider from "@/context/table-ctx";

import Aside from "@/components/aside/aside";
import Header from "@/components/header/header";
import Navigation from "@/components/table/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Navigation />
        <div className="flex flex-row">
          <div className="sm:basis-[10%]">
            <Aside />
          </div>
          <div className="flex sm:basis-[90%] shrink flex-col items-center justify-center static">
            <AsideCTXProvider>{children}</AsideCTXProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
