import type { Metadata , Viewport } from 'next';
import { Inter } from 'next/font/google';

import './globals.css';
import { Toaster } from 'sonner';

import Aside from '@/components/aside/aside';
import Header from '@/components/header/header';
import Navigation from '@/components/table/navigation';
import AsideCTXProvider from '@/context/table-ctx';


const inter = Inter({ subsets: ['latin'] });

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster richColors theme="dark" />

        <Header />
        <Navigation />
        <div className="flex flex-row">
          {/* TODO: Rework this. */}
          <div className="sm:basis-[10%]">
            <Aside />
          </div>
          <div className="flex shrink flex-col items-center justify-center sm:basis-[90%]">
            <AsideCTXProvider>{children}</AsideCTXProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
